Fixes #19147: Email notification should be disabled when no host server is configured
Normation/rudder-plugins pull request #364
Opened 2021-04-26 07:56 UTC by ElaadF

https://issues.rudder.io/issues/19147

2021-04-29 14:23 UTC, Fdall requested changes

2021-04-29 14:23 UTC, Fdall commented on change-validation/src/main/resources/template/ChangeValidationManagement.html
> +            By default, email notification are disabled. To enable it make sure that <b>smtp.hostServer</b> parameter is
```suggestion
            By default, email notifications are disabled. To enable it make sure that the <b>smtp.hostServer</b> parameter is
```

2021-04-29 14:23 UTC, Fdall commented on change-validation/src/main/resources/template/ChangeValidationManagement.html
> +            By default, email notification are disabled. To enable it make sure that <b>smtp.hostServer</b> parameter is
```suggestion
            By default, email notifications are disabled. To enable it make sure that the <b>smtp.hostServer</b> parameter is
```

2021-04-29 14:28 UTC, ElaadF commented on change-validation/src/main/resources/template/ChangeValidationManagement.html
> +            By default, email notification are disabled. To enable it make sure that <b>smtp.hostServer</b> parameter is
also : duplicated paragraph

2021-04-30 06:40 UTC, ElaadF commented
Commit modified

2021-05-21 08:49 UTC, VinceMacBuche approved these changes

2021-05-31 09:40 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2021-05-31 09:40 UTC, merged