Fixes #19401: Add an ldapsearch example in config file for LDAP auth
Normation/rudder-plugins pull request #381
Opened 2021-06-07 14:14 UTC by fanf

https://issues.rudder.io/issues/19401

2021-06-07 14:36 UTC, Fdall requested changes

2021-06-07 14:36 UTC, Fdall commented on auth-backends/README.adoc
> +# what means that each user should have access to Rudder MUST have a line in that file.
```suggestion
# meaning that each user should have access to Rudder MUST have a line in that file.
```

2021-06-07 14:36 UTC, Fdall commented on auth-backends/README.adoc
> +# - an authentication error here means that your rudder service user doesn't havent the
```suggestion
# - an authentication error here means that your rudder service user does not have the
```

2021-06-07 14:36 UTC, Fdall commented on auth-backends/README.adoc
> +#   rights to do a search and won't be able to find the corresponding user full DN;
```suggestion
#   rights to do a search and will not be able to find the corresponding user full DN;
```

2021-06-07 14:36 UTC, Fdall commented on auth-backends/README.adoc
> +# - you should get exactly one result: the dn to use in the second request. If you don't
```suggestion
# - you should get exactly one result: the DN to use in the second request. If you don't
```

2021-06-07 14:36 UTC, Fdall commented on auth-backends/README.adoc
> +#   get any results, check the base DN for search and the LDAP filter.
```suggestion
#   get any results, check the base DN and the LDAP filter.
```

2021-06-07 14:36 UTC, Fdall commented on auth-backends/README.adoc
> +# "application" dn for Rudder in you LDAP directory, or an LDAP user with
```suggestion
# "application" DN for Rudder in you LDAP directory, or an LDAP user with
```

2021-06-07 16:10 UTC, fanf commented
PR updated with a new commit

2021-06-11 15:18 UTC, fanf commented
OK, squash merging this PR

2021-06-11 15:18 UTC, merged