Fixes #25999: Disabling user rest API token feature from api-authorizations plugin UI
Normation/rudder-plugins pull request #775
Opened 2024-12-03 18:19 UTC by clarktsiory

https://issues.rudder.io/issues/25999

2024-12-03 18:40 UTC, clarktsiory commented
PR updated with a new commit

2024-12-07 09:19 UTC, fanf commented
After further consideration, we wan to totally disable (not show) the pop-up when the feature is disabled (globally or for an user), as if the feature was not here.

2024-12-07 09:21 UTC, fanf requested changes
After further consideration, we wan to totally disable (not show) the pop-up when the feature is disabled (globally or for an user), as if the feature was not here.

2024-12-12 16:06 UTC, clarktsiory commented
PR rebased

2024-12-12 22:31 UTC, fanf approved these changes
Perfect !

2024-12-12 22:32 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-plugins/pull/775`
-- Your faithful QA
Kant merge: "In law a man is guilty when he violates the rights of others. In ethics he is guilty if he only thinks of doing so."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/94304/console)

2024-12-16 09:00 UTC, clarktsiory commented
OK, merging this PR

2024-12-16 09:00 UTC, merged

2024-12-16 09:01 UTC, clarktsiory commented
OK, merging this PR