Fixes #26065: OpenSCAP report needs to be rendered without iframe with sanitized html
Normation/rudder-plugins pull request #779
Opened 2024-12-13 14:04 UTC by clarktsiory

https://issues.rudder.io/issues/26065

We have to read the report file (as the API does) in the snippet, as pass the information down, to create buttons with a download action (similar to https://github.com/Normation/rudder/pull/5941).

The iframe can be used to render the original report by putting the sanitized content as string in [the srcdoc attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#srcdoc)

Result : 
![Screenshot from 2024-12-13 16-16-40](https://github.com/user-attachments/assets/cf837460-c3d6-4057-9af9-c2be430e3f49)

2024-12-13 14:05 UTC, clarktsiory commented
Commit modified

2024-12-13 14:06 UTC, clarktsiory commented
Commit modified

2024-12-13 14:06 UTC, clarktsiory commented
Commit modified

2024-12-13 14:27 UTC, fanf requested changes

2024-12-13 14:27 UTC, fanf commented on openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
> +        <span><i class="fa fa-download text-light"></i>Download report</span>,
We don't want a download here, we want to open a tab with the report. That allows to see it in full page, with link navigation available, which is mandatory to be able to see anything.

2024-12-13 15:16 UTC, clarktsiory commented
PR updated with a new commit

2024-12-14 20:07 UTC, fanf approved these changes

2024-12-14 20:08 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2024-12-14 20:08 UTC, merged